### ISSUE TITLE
Implementation with React Loadable

### ISSUE THREAD

**Issue by cereallarceny** [kirill-konshin/react-router-redux-middleware#11]
Is there any reason that this library couldn't work with [`react-loadable`](https://github.com/jamiebuilds/react-loadable)?  It seems to me that their section on [Server side rendering](https://github.com/jamiebuilds/react-loadable#------------server-side-rendering) should work perfectly fine.  [Even the documentation on React Router 4 seems to indicate now that this is possible.](https://reacttraining.com/react-router/web/guides/code-splitting/code-splitting-and-server-side-rendering)

I believe your documentation could be out of date.  Do you have an example of this *not* working?

**Comment by kirill-konshin** [comment]
In general, the main concern is always how to make sure that resolved HTML and state will match client DOM and state with lazy loaded pages. Potentially there could be conflicts.

I am not aware why this lib can't work with loadable, I never tried to use both at the same time. So if you can provide a case, I'd have something actionable.
