### ISSUE TITLE
Window is not defined

### ISSUE THREAD

**Issue by trixden** [kirill-konshin/react-router-redux-middleware#13]
Hi. How to solve problem with window global variable?

`ReferenceError: window is not defined`

I understand, `window` and `document` is not defined on the server. But, this variables very useful for my project, and installed packages.

**Comment by kirill-konshin** [comment]
Don’t use window on server :) it is a really bad practice. How will you transfer things that were set there to client to recover state?

If you decide to use it anyway just set it on global object:

‘’’js
if (typeof window === ‘undefined’) global.window = {};
‘’’

**Comment by trixden** [comment]
@kirill-konshin I know. But, many packages use `window` and even more `document`. Basically to initialize scripts. I understand you. Thanks.
