### ISSUE TITLE
Cannot run create-react-app example

### ISSUE THREAD

**Issue by gargsms** [kirill-konshin/react-router-redux-middleware#9]
I keep on getting this on the `create-react-app` example
```
Error: Cannot find module 'react-dom/server'
Use "create-react-server --help"
```

I installed `react-dom` independently in the `examples`, the `create-react-server` folders, but it still wouldn't go away.

`npm -v : 5.2.0`
`node -v : v6.11.3`

**Comment by kirill-konshin** [comment]
Thank you for reporting, I will check.

**Comment by kirill-konshin** [comment]
Per [readme](https://github.com/kirill-konshin/create-react-server#examples) you need to do `npm install` in both main root folder and examples in order to make it work.
